
package studentenrollmentsystem;

import msAccessConnection.UserDbAccess;
import msAccessConnection.DatabaseConnection;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import studentenrollmentsystem.StudentFrame;

public class RegistrationUI extends javax.swing.JFrame {

    private UserDbAccess userDAO;
    private int mouseX, mouseY;
    
    public RegistrationUI() {
        initComponents();
        setLocationRelativeTo(null);
        userDAO = new UserDbAccess(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        passTxtField = new javax.swing.JTextField();
        regButton = new javax.swing.JButton();
        passLabel = new javax.swing.JLabel();
        emailTxtField = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lnameTxtfield = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        ageTextfield = new javax.swing.JTextField();
        nameLabel1 = new javax.swing.JLabel();
        nameLabel2 = new javax.swing.JLabel();
        genderCombobox = new javax.swing.JComboBox<>();
        nameLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        loginButton = new javax.swing.JLabel();
        bdayPicker = new com.github.lgooddatepicker.components.DatePicker();
        fnameTxtfield = new javax.swing.JTextField();
        m_inameTxtfield1 = new javax.swing.JTextField();
        nameLabel4 = new javax.swing.JLabel();
        nameLabel5 = new javax.swing.JLabel();
        exitbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setUndecorated(true);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/NRG Enrollment System.png"))); // NOI18N
        jLabel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 490));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));

        passTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passTxtFieldActionPerformed(evt);
            }
        });

        regButton.setText("Register");
        regButton.setBackground(new java.awt.Color(0, 102, 153));
        regButton.setForeground(new java.awt.Color(255, 255, 255));
        regButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regButtonActionPerformed(evt);
            }
        });

        passLabel.setText("Password");
        passLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        passLabel.setForeground(new java.awt.Color(0, 51, 102));

        emailTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtFieldActionPerformed(evt);
            }
        });

        emailLabel.setText("Email");
        emailLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(0, 51, 102));

        jLabel3.setFont(new java.awt.Font("Meiryo UI", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 204));
        jLabel3.setText("Create an account");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lnameTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameTxtfieldActionPerformed(evt);
            }
        });

        nameLabel.setText("Last Name");
        nameLabel.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(0, 51, 102));

        ageTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTextfieldActionPerformed(evt);
            }
        });

        nameLabel1.setText("Age");
        nameLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel1.setForeground(new java.awt.Color(0, 51, 102));

        nameLabel2.setText("Gender");
        nameLabel2.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel2.setForeground(new java.awt.Color(0, 51, 102));

        genderCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        nameLabel3.setText("Birthday");
        nameLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel3.setForeground(new java.awt.Color(0, 51, 102));

        jLabel2.setText("Already have an account?");

        loginButton.setText("Login");
        loginButton.setForeground(new java.awt.Color(0, 102, 204));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        bdayPicker.setBackground(new java.awt.Color(255, 255, 255));

        fnameTxtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameTxtfieldActionPerformed(evt);
            }
        });

        m_inameTxtfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_inameTxtfield1ActionPerformed(evt);
            }
        });

        nameLabel4.setText("First Name");
        nameLabel4.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel4.setForeground(new java.awt.Color(0, 51, 102));

        nameLabel5.setText("Middle Name");
        nameLabel5.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 12)); // NOI18N
        nameLabel5.setForeground(new java.awt.Color(0, 51, 102));

        exitbtn.setText("Exit");
        exitbtn.setBackground(new java.awt.Color(255, 255, 255));
        exitbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        exitbtn.setForeground(new java.awt.Color(255, 0, 51));
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(111, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLabel)
                                .addComponent(emailLabel)
                                .addComponent(passLabel)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(passTxtField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLabel1)
                                            .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLabel2)
                                            .addComponent(genderCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nameLabel3)
                                            .addComponent(bdayPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(emailTxtField, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addGap(104, 104, 104))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(regButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(155, 155, 155))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(fnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(nameLabel4))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nameLabel5)
                                .addComponent(m_inameTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(exitbtn)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel)
                    .addComponent(nameLabel4)
                    .addComponent(nameLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fnameTxtfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_inameTxtfield1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(nameLabel2)
                    .addComponent(nameLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(genderCombobox)
                        .addComponent(bdayPicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ageTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addGap(2, 2, 2)
                .addComponent(emailTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regButton)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(loginButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitbtn)
                .addGap(428, 428, 428))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 510, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passTxtFieldActionPerformed

    private void emailTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtFieldActionPerformed

    private void lnameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameTxtfieldActionPerformed

    private void ageTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTextfieldActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginButtonMouseClicked
        // TODO add your handling code here:
       LoginUI login = new LoginUI();
       login.setVisible(true);
       dispose();
    }//GEN-LAST:event_loginButtonMouseClicked

    private void regButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regButtonActionPerformed
    String lname = lnameTxtfield.getText().trim();
    String fname = fnameTxtfield.getText().trim();
    String mname = m_inameTxtfield1.getText().trim();
    String ageStr = ageTextfield.getText().trim();
    int age = 0;
    try {
        age = Integer.parseInt(ageStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Please enter a valid age.");
        return;
    }
    String gender = (String) genderCombobox.getSelectedItem();
    LocalDate birthday = bdayPicker.getDate();
    String email = emailTxtField.getText().trim();
    String password = passTxtField.getText().trim();

    // Validate required fields
    if (lname.isEmpty() || fname.isEmpty() || ageStr.isEmpty() || email.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please fill in all required fields.");
        return;
    }

    boolean registered = userDAO.registerUser(lname, fname, mname, age, gender, formatDate(birthday), email, password);

   if (registered) {
    StudentFrame sframe = new StudentFrame();
    JOptionPane.showMessageDialog(null, "Registration successful!");
    sframe.setVisible(true);
    clearFields();
    dispose();
} else {
    JOptionPane.showMessageDialog(null, "Registration failed!");
}

    }//GEN-LAST:event_regButtonActionPerformed
    


     private void clearFields() {
        lnameTxtfield.setText("");
        ageTextfield.setText("");
        genderCombobox.setSelectedIndex(0); // Assuming Male is the default
        bdayPicker.setDate(null);
        emailTxtField.setText("");
        passTxtField.setText("");
    }

    // Method to format Date to String
    private String formatDate(LocalDate date) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("MM/dd/yyyy");
        return date.format(formatter);
}
    
    
    private void fnameTxtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameTxtfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameTxtfieldActionPerformed

    private void m_inameTxtfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_inameTxtfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_inameTxtfield1ActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        dispose();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_formMouseDragged

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextfield;
    private com.github.lgooddatepicker.components.DatePicker bdayPicker;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTxtField;
    private javax.swing.JButton exitbtn;
    private javax.swing.JTextField fnameTxtfield;
    private javax.swing.JComboBox<String> genderCombobox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lnameTxtfield;
    private javax.swing.JLabel loginButton;
    private javax.swing.JTextField m_inameTxtfield1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel2;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel nameLabel4;
    private javax.swing.JLabel nameLabel5;
    private javax.swing.JLabel passLabel;
    private javax.swing.JTextField passTxtField;
    private javax.swing.JButton regButton;
    // End of variables declaration//GEN-END:variables
}
